### ISSUE TITLE
catkin for cmake?

### ISSUE THREAD

**Issue by lin-name** [mees/tracking_sdf#1]
Hello，professor. 
I want to build this project on windows10, cmake 3.16.0, Visual Studio 2019. When build, the cmake output:  

 **By not providing "Findcatkin.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "catkin", but
  CMake did not find one. 
Could not find a package configuration file provided by "catkin" with any
  of the following names:

    catkinConfig.cmake
    catkin-config.cmake

  Add the installation prefix of "catkin" to CMAKE_PREFIX_PATH or set
  "catkin_DIR" to a directory containing one of the above files.  If "catkin"
  provides a separate development package or SDK, be sure it has been
  installed.**

Is catkin necessary for this project?  How can i get the catkin source code? And which versions? Any suggestions would be helpful.
Looking forward for your reply!

**Comment by mees** [comment]
Hi there,
the underlying dependency is ROS (https://ros.org/), which provides catkin and most of the other dependencies. I am not sure if this code will run with the latest ros versions, as we wrote this in 2014, but to compile the package you need ros.
